require 'kickstart.plugins.pkg'
require 'kickstart.keymap.settings'
require 'kickstart.keymap.lsp'
require 'kickstart.keymap.telescope'
require 'kickstart.keymap.treesitter'
require 'kickstart.keymap.completion'
require 'kickstart.keymap.which'
